### ISSUE TITLE
Action产物中，Windows的构建包需要在Mingw下才能正常执行

### ISSUE THREAD

**Issue by i-moxi** [Enter-tainer/cxx2flow#1]
直接在CMD中执行程序报 0xc000007b 错误，查阅错误码得知是执行文件格式错误。
于是试着在Mingw里面执行...打开了...
应该不算预期打包的行为

**Comment by Enter-tainer** [comment]
https://github.com/Enter-tainer/cxx2flow/actions/runs/1141746959

可以看一下这里的 Windows binary 可以运行吗，我手里暂时没有 windows 设备

**Comment by Enter-tainer** [comment]
我找了个Windows机器试了一下没问题，暂时先 close 掉
