### ISSUE TITLE
命令行模式处理 if-else语句报错

### ISSUE THREAD

**Issue by houcy** [Enter-tainer/cxx2flow#42]
您好，
命令行处理下面的代码报错“unexpected dumy ast node”，但是用图形界面gui软件就可以识别if-else语句，麻烦大神修复一下命令行的问题，谢谢！

`#include <iostream>
using namespace std;

int main(){
       int a = 10, b = 5;
        if(a > b) {
            cout << "ok";
        } else {
            cout << "bad";
        }
        return 0;
}`
[
![1699423362166](https://github.com/Enter-tainer/cxx2flow/assets/6321061/9ceb2c78-6b7f-4f1b-a5bf-db3a76e48804)
](url)

![333](https://github.com/Enter-tainer/cxx2flow/assets/6321061/14b69b86-6206-4291-9a5e-12dc18689659)

**Comment by Enter-tainer** [comment]
<img width="493" alt="image" src="https://github.com/Enter-tainer/cxx2flow/assets/25521218/af666d0e-925c-4f58-b71e-6322a9936acd">

我本地测试cli能跑

**Comment by Enter-tainer** [comment]
我刚刚升级了一下依赖，发了一个新版，你可以试试

**Comment by houcy** [comment]
c++代码还是有问题，用新版本0.6.1测试了
Error: cxx2flow::unexpected_dummy_ast

  × unexpected dummy ast node
    ╭─[main.cpp:6:1]
  6 │             cout << "yes";
  7 │ ╭─▶     } else {
  8 │ │           cout << "no";
  9 │ ├─▶     }
    · ╰──── dummy ast node here
 10 │         return 0;
    ╰────
  help: dummy node found in the ast
        this might be a bug, please report it to the author

**Comment by Enter-tainer** [comment]
你发一下你完整代码，我用你的代码测了没问题

**Comment by Enter-tainer** [comment]
哦你说c++。。我不记得我有没有对后缀名做什么特判了，你把后缀改成 .c 能行吗

**Comment by Enter-tainer** [comment]
看了下代码，好像也没有啊。。你要不发一下你的代码文件和你运行的命令吧
