### ISSUE TITLE
希望出一个web端的

### ISSUE THREAD

**Issue by Tiang-88** [Enter-tainer/cxx2flow#44]
这样各个平台都方便使用。再就是mac版的gui有问题，测试电脑m1 pro

**Comment by Enter-tainer** [comment]
mac的gui构建现在应该是只有x86的，web端的做不了

**Comment by Enter-tainer** [comment]
看了下好像现在没有mac的构建，你自己把代码拉下来编译试试吧，我不确定能不能行

**Comment by Enter-tainer** [comment]
所以你是在哪看到这个项目的？
