### ISSUE TITLE
exe文件打不开啊？是要进行什么处理吗？

### ISSUE THREAD

**Issue by paperplane123** [Enter-tainer/cxx2flow#5]
打开exe闪退

**Comment by Enter-tainer** [comment]
请在命令行中运行，而不是直接双击打开

**Comment by paperplane123** [comment]
啊？命令行里怎么运行？start .exe？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wenzhuo Liu ***@***.***&gt;
发送时间: 2022年4月6日 14:40
收件人: Enter-tainer/cxx2flow ***@***.***&gt;
抄送: paperplane123 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Enter-tainer/cxx2flow] exe文件打不开啊？是要进行什么处理吗？ (Issue #5)





 
请在命令行中运行，而不是直接双击打开

**Comment by Enter-tainer** [comment]
你可以尝试一下GUI版，不会命令行也可以使用 https://github.com/Enter-tainer/cxx2flow-gui/releases/tag/v0.1.1

**Comment by Enter-tainer** [comment]
appimage 是给 linux 用的，如果你是windows的话，应该使用 msi

**Comment by imasmo** [comment]
我在windows系统上安装msi，点击开始安装后，中途总是提示安装失败，不知道什么原因。

**Comment by Enter-tainer** [comment]
> 我在windows系统上安装msi，点击开始安装后，中途总是提示安装失败，不知道什么原因。

可以提供一下截图吗
