### ISSUE TITLE
能不能输出graphviz支持的数据格式

### ISSUE THREAD

**Issue by haoliu001** [Enter-tainer/cxx2flow#50]
你好，

我想得到一下函数结构的数据比如每个节点以及节点包含的命令，而不仅仅是一个图片。可以帮一下忙么

**Comment by Enter-tainer** [comment]
这个不是已经支持了吗

**Comment by haoliu001** [comment]
可不可以给个样例呀，我看到只能生成png和svg格式（我不太清楚这两种格式怎么输入到graphviz里面）
