### ISSUE TITLE
作者您好，后面会支持对函数内部的解析吗？

### ISSUE THREAD

**Issue by Tiang-88** [Enter-tainer/cxx2flow#55]
作者您好，后面会支持对函数内部的解析吗？比如目前的流程图只能解析main里面的代码过程，不能解析自定义函数。希望自定义函数内部也可以解析。比如下图，没解析prime函数内部的流程
![image](https://github.com/user-attachments/assets/26aef991-d355-4b43-86f7-aa16205af9ff)

**Comment by ArvinChengcheng** [comment]
这个不是可以定义解析哪个函数吗？！

**Comment by ArvinChengcheng** [comment]
默认值是main而已

**Comment by Enter-tainer** [comment]
这个之前好像在别的issue里面已经问过一次了？不要重复开issue
