### ISSUE TITLE
Error report: #if #else #endif generate error

### ISSUE THREAD

**Issue by ArvinChengcheng** [Enter-tainer/cxx2flow#56]
![image](https://github.com/user-attachments/assets/33f809e2-45bd-4f77-9027-fa070246d3cb)
At least one of them should be identified: #if  or #else

**Comment by ArvinChengcheng** [comment]
and more, it can't identify the #if 0.....
![image](https://github.com/user-attachments/assets/ae4a4ca4-9c89-4640-a7f4-4f45adddca62)

**Comment by Enter-tainer** [comment]
they are macros... and they shouldnt be included in flowchart.

**Comment by ArvinChengcheng** [comment]
but at least should identify the "#if 0"

**Comment by Enter-tainer** [comment]
the key is that cxx2flow doesnt recognize macros at all. so anything can happen. it has a `--cpp` option to use external c pre processor to clean up the macros though.

**Comment by ArvinChengcheng** [comment]
OK, could you please short to teach me about how to install cpp in windows? or raise a web address, so that I can learnning.

**Comment by Enter-tainer** [comment]
cpp comes with gcc or clang. you might want to need install one of them.

**Comment by ArvinChengcheng** [comment]
It lose the inform of Macro_name(it's hard to read) when I generate .dot with a pre-compiled .c file
![image](https://github.com/user-attachments/assets/adde7b62-c10b-46ba-89df-39a3def10972)
![image](https://github.com/user-attachments/assets/4a0686a7-09b7-48d8-b181-a0e6a0115e4e)

**Comment by Enter-tainer** [comment]
I'm afraid that cxx2flow cannot smartly expand your macros depending on whether if they are hard to read or not.

**Comment by Enter-tainer** [comment]
It's possible but can be very cumbersome to implement. I'm focusing on work and don't have time to look on it. PR is welcome.

**Comment by ArvinChengcheng** [comment]
just an advice. 😄
