### ISSUE TITLE
关于自定义函数问题

### ISSUE THREAD

**Issue by Tiang-88** [Enter-tainer/cxx2flow#57]
您好作者，又打扰您了
代码：
```cpp

using namespace std;
int prime(long long x){
    bool flag=1;
    for(int i=2;i<=sqrt(x);i++){
        if(x%i==0){
            flag=0;
            break;
        }
    }
    if(flag){
        cout<<'T'<<endl;
    }else{
        cout<<'F'<<endl;
    }
    return 0;
}
int main(){
    long long x;
    cin>>x;
    
    prime(x);
    return 0;
}
```
Usage: cxx2flow [OPTIONS] [INPUT] [FUNCTION]

Arguments:
  [INPUT]     Sets the path of the input file. e.g. test.cpp
              If not specified, cxx2flow will read from stdin.
  [FUNCTION]  The function you want to convert. e.g. main [default: main]
  我看了说明书，这里可以指定自定义函数解析。但我的问题是比如一个代码里面有好几个函数，我需要都解析到一个流程图。
  解析 main 函数：
比如这样
cxx2flow test.cpp main -o main.dot
解析 prime 函数：
cxx2flow test.cpp prime -o prime.dot
但是这样出来的结果是2个图片。
可不可以这样：解析cpp文件中多个函数在一个图片中，哪怕分离的也好。
<img width="406" alt="image" src="https://github.com/user-attachments/assets/28fe525c-219d-402a-b739-08a73687085a">

谢谢您

**Comment by Enter-tainer** [comment]
暂时不考虑，这个工具还是focus在单个函数上
